============================= test session starts ==============================
platform linux -- Python 3.9.14, pytest-7.1.3, pluggy-1.0.0
rootdir: /workspace
collected 14 items
tests/test_a_environment.py .                                            [  7%]
tests/test_a_setup.py .                                                  [ 14%]
tests/test_distances.py ...                                              [ 35%]
tests/test_generate_regression_data.py F                                 [ 42%]
tests/test_knn.py .F..F                                                  [ 78%]
tests/test_metrics.py .                                                  [ 85%]
tests/test_polynomial_regression.py ..                                   [100%]
=================================== FAILURES ===================================
________________________ test_generate_regression_data _________________________
>                   assert good_mse > prev_good_mse, msg
E                   AssertionError: With degree 2 and 10000 examples, expected 7.319 > 27.519
E                   assert 7.319406802233987 > 27.519154825857242
tests/test_generate_regression_data.py:29: AssertionError
_______________________________ test_knn_k_is_1 ________________________________
>                   accuracy = run(datasets[key], fraction,
                                   n_neighbors=1,
                                   distance_measure=distance_measure,
                                   aggregator="mode")
tests/test_knn.py:66:
>               labels[i] = self.train_targets[index[0]]
E               IndexError: index 0 is out of bounds for axis 0 with size 0
src/k_nearest_neighbor.py:87: IndexError
_____________________________ test_knn_regression ______________________________
>               assert np.all(prev_k_mses <= new_k_mses), msg
E               AssertionError: Increasing k to 5 should increase mse, but [0.2  0.01] > [0.65 0.  ]
E               assert False
E                +  where False = <function all at 0x7fe9e16749d0>(array([0.20344893, 0.01384754]) <= array([0.65414034, 0.00123445]))
E                +    where <function all at 0x7fe9e16749d0> = np.all
tests/test_knn.py:157: AssertionError
=============================== warnings summary ===============================
tests/test_knn.py::test_knn_k_is_1
  /workspace/src/distances.py:76: RuntimeWarning: invalid value encountered in double_scalars
    S = upper/down
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_generate_regression_data.py::test_generate_regression_data
FAILED tests/test_knn.py::test_knn_k_is_1 - IndexError: index 0 is out of bou...
FAILED tests/test_knn.py::test_knn_regression - AssertionError: Increasing k ...
=================== 3 failed, 11 passed, 1 warning in 6.64s ====================